"""Deterministic task templates for a customer's life-transition plan."""

HOME_PURCHASE_TASKS = [
    {
        "id": "mortgage",
        "title": "Arrange mortgage",
        "description": "Confirm financing before the purchase is final.",
        "phase": "this_week",
        "priority": "high",
        "due_offset_days": -14,
        "owner": "customer",
    },
    {
        "id": "home_insurance",
        "title": "Choose home insurance",
        "description": "Make sure cover starts when you take possession of the home.",
        "phase": "this_week",
        "priority": "high",
        "due_offset_days": -7,
        "owner": "customer",
    },
    {
        "id": "condominium_add_on",
        "title": "Check condominium insurance add-on",
        "description": "Relevant when you buy a condominium/apartment.",
        "phase": "this_week",
        "priority": "medium",
        "due_offset_days": -7,
        "owner": "customer",
    },
    {
        "id": "purchase_agreement",
        "title": "Receive Purchase Agreement",
        "description": "Get the seller-signed purchase agreement (köpekontrakt) before applying for your Loan Offer.",
        "phase": "secure_mortgage",
        "priority": "high",
        "due_offset_days": -21,
        "owner": "customer",
    },
    {
        "id": "loan_offer",
        "title": "Secure Loan Offer",
        "description": "Apply for your final mortgage approval (Lånelöfte to Loan Offer) once you have a purchase agreement.",
        "phase": "secure_mortgage",
        "priority": "high",
        "due_offset_days": -14,
        "owner": "customer",
    },
    {
        "id": "electricity",
        "title": "Set up electricity contract",
        "description": "Arrange electricity before moving in.",
        "phase": "before_move_in",
        "priority": "high",
        "due_offset_days": -7,
        "owner": "customer",
    },
    {
        "id": "broadband",
        "title": "Choose broadband",
        "description": "Check which providers serve the property and allow time for installation.",
        "phase": "before_move_in",
        "priority": "medium",
        "due_offset_days": -14,
        "owner": "customer",
    },
    {
        "id": "housing_fee",
        "title": "Understand the housing-cooperative fee",
        "description": "Check the monthly fee separately from the mortgage payment.",
        "phase": "before_move_in",
        "priority": "medium",
        "due_offset_days": -7,
        "owner": "customer",
    },
    {
        "id": "life_insurance",
        "title": "Review life insurance",
        "description": "Consider how a household could manage the loan if income changes unexpectedly.",
        "phase": "later",
        "priority": "medium",
        "due_offset_days": 30,
        "owner": "customer",
    },
    {
        "id": "loan_protection",
        "title": "Review loan protection",
        "description": "Understand protection options if illness or unemployment affects repayments.",
        "phase": "later",
        "priority": "low",
        "due_offset_days": 30,
        "owner": "customer",
    },
    {
        "id": "emergency_savings",
        "title": "Build emergency savings",
        "description": "Set aside a buffer for unexpected home costs.",
        "phase": "later",
        "priority": "low",
        "due_offset_days": 60,
        "owner": "customer",
    },
]

PLAN_TEMPLATES = {"home_purchase": HOME_PURCHASE_TASKS}
